/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        canvas: {
          light: '#F7F7F5',
          dark: '#0C0F14',
          basalt: '#0C0F14',
          abyssal: '#080C12',
          surface: '#111319',
        },
        realm: {
          bg: '#111319',
          surface: '#161B22',
          container: '#1D2025',
          elevated: '#272A30',
          highest: '#32353B',
          recessed: '#080C12',
          gold: '#C5A059',
          goldLight: '#E9C176',
          goldMuted: '#775A19',
          bronze: '#8C6D46',
          bronzeLight: '#E6C093',
          bronzeDark: '#4E4639',
          ember: '#D97736',
          emberLight: '#FFB68C',
          emberGlow: '#F28B48',
          parchment: '#E6DFD5',
          parchmentMuted: '#9A8F80',
          stoneBorder: '#272A30',
          bronzeBorder: '#4E4639',
        },
        surface: {
          light: '#FFFFFF',
          dark: '#161B22',
          elevatedLight: '#EFEFEB',
          elevatedDark: '#272A30',
        },
        ink: {
          primary: '#111111',
          primaryDark: '#E6DFD5',
          secondary: '#6B6B67',
          secondaryDark: '#9A8F80',
          muted: '#8E8E89',
          mutedDark: '#6E6B65',
        },
        borderLine: {
          light: '#DCDCD7',
          dark: '#272A30',
          subtleLight: '#E8E8E3',
          subtleDark: '#1E232A',
        },
        accent: {
          DEFAULT: '#C5A059',
          dark: '#E9C176',
          hover: '#B59048',
          glow: 'rgba(197, 160, 89, 0.15)',
          bronze: '#8C6D46',
          ember: '#D97736',
        },
      },
      fontFamily: {
        serif: ['"Noto Serif"', 'Georgia', 'serif'],
        sans: ['Inter', 'Geist', '-apple-system', 'BlinkMacSystemFont', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'monospace'],
      },
      letterSpacing: {
        tightest: '-0.035em',
        tighter: '-0.02em',
        tight: '-0.01em',
        normal: '0',
        wide: '0.025em',
        wider: '0.05em',
        widest: '0.1em',
        monumental: '0.16em',
      },
      animation: {
        'pulse-subtle': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'ember-float': 'emberFloat 8s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}
